# Site settings
title: knoxschools.us
subtitle: real news
email: info@knoxschools.us
description: Real school news that matters
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://knoxschools.us" # the base hostname & protocol for your site
author: CB & GC
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed

writers:
  Cade Brown: cade@cade.site
  Gregory Croisdale: greg@gregc.us

